### ISSUE TITLE
Need fix. 

### ISSUE THREAD

**Issue by WindofRus** [Catana791/Asthosus#97]
Game version - 146.
Mod version - Asthosus-1.5.2.

Wesmonium Accumulator does not have 900% efficiency.

![1](https://github.com/user-attachments/assets/b013b951-42c5-401d-aca3-07bb9cb27591)

I demand a fix.

**Comment by Catana791** [comment]
This is due to the Accultor having a maximum boost of 100% per tile. 

Due to it being a 3x3 block (=9 times) it becomes 900% (100% x 9 tiles = 900% total).

The boost, however, is capped at a reasonable value. 
Thus, this is purely a display/graphic issue that doesn't impact the game experience in any way.

I can look into changing that 900% text but have it known that this is of no priority, especially since the development of this mod is still on halt as I am taking very much needed break.

**Comment by WindofRus** [comment]
When Build this block on white surface he show 225%, not a 900%, check this.

**Comment by BSp-2** [comment]
> When Build this block on white surface he show 225%, not a 900%, check this.

Ты хоть пытался перевести то что написал катсер??? Вообще такое чувство что ты проигнорировал его сообщение свыше и написал тоже самое что и перед этим наверху

**Comment by Kev-Vily** [comment]
> When Build this block on white surface he show 225%, not a 900%, check this. 

bro's aren't even read caster's explanation
